export let common = [
  {
    table: 'cust_company',
    id: 'com_name',
    text: '公司',
    text_en: 'Company',
    key: 'com_name',
    value: '',
    rules: 'require',
    components: 'com-name',
  },
  {
    table: 'cust_company',
    id: 'cust_no',
    text: '编号',
    text_en: 'NO.',
    key: 'cust_no',
    value: '',
    rules: 'require',
    components: 'cust-no',
  },
  {
    table: 'cm_companys',
    id: 'credit_rating',
    text: '信用等级',
    text_en: 'Credit Level',
    key: 'mg_credit',
    value: {
      mg_rating: '',
    },
    rules: 'require',
    components: 'credit-level',
  },
  {
    table: 'cust_company',
    id: 'com_nick',
    text: '简称',
    text_en: 'Abbreviation',
    key: 'com_nick',
    value: '',
    rules: 'require',
    components: 'com-nick',
  },
  {
    table: 'cust_company',
    id: 'com_address',
    text: '地址',
    text_en: 'Address',
    key: 'address',
    value: '',
    rules: 'require',
    bill_check: 'sc',
    components: 'cust-address',
  },
  {
    table: 'cust_company',
    id: 'cust_owner_id',
    text: '客户经理',
    text_en: 'Account',
    key: 'owner_id',
    value: '',
    rules: 'require',
    components: 'cust-owner',
  },
  {
    table: 'cust_company',
    id: 'busi_group_id',
    text: '部门',
    text_en: 'Department',
    key: 'busi_group_id',
    value: '',
    rules: 'require',
  },
  // {
  //   table: 'cm_companys',
  //   id: 'charge_commission_cust_id',
  //   text: '明佣支付对象',
  //   text_en: '明佣支付对象',
  //   key: 'mg_charge',
  //   value: {
  //     commission_cust_id: '',
  //   },
  //   rules: 'require',
  // },
  // {
  //   table: 'cm_companys',
  //   id: 'charge_kickback_cust_id',
  //   text: '支付对象',
  //   text_en: '支付对象',
  //   key: 'mg_charge',
  //   value: {
  //     kickback_cust_id: '',
  //   },
  //   rules: 'require',
  // },
  {
    table: 'cm_companys',
    id: 'charge_discount_rate',
    text: '明佣',
    text_en: 'Commission',
    key: 'mg_charge',
    value: {
      discount_rate: '',
    },
    rules: 'require',
    components: 'discount-rate',
  },
  {
    table: 'cm_companys',
    id: 'charge_commission_rate',
    text: '其他费用',
    text_en: 'Other charge',
    key: 'mg_charge',
    value: {
      commission_rate: '',
    },
    rules: 'require',
    components: 'other-fee',
  },
  {
    table: 'cm_companys',
    id: 'inspection_request',
    text: '验货要求',
    text_en: 'Inspection requirements',
    key: 'mg_inspection_request',
    value: '',
    rules: 'require',
    components: 'check-require',
  },
  {
    table: 'cust_company',
    id: 'com_phone',
    text: '公司电话',
    text_en: 'Company phone',
    key: 'com_phone',
    value: '',
    rules: 'require',
    components: 'com-phone',
  },
  // {
  //   table: 'cm_companys',
  //   id: 'commission_upload',
  //   text: '明佣协议',
  //   text_en: '明佣协议',
  //   key: 'mg_commission_upload',
  //   value: '',
  //   rules: 'require',
  // },
  {
    table: 'cust_company',
    id: 'country_id',
    text: '国家',
    text_en: 'Country',
    key: 'country_id',
    value: '',
    rules: 'require',
    components: 'cust-country',
  },
  {
    table: 'cm_companys',
    id: 'city_id',
    text: '所在城市',
    text_en: 'City',
    key: 'mg_city',
    value: '',
    rules: 'require',
    components: 'cust-city',
  },
  {
    table: 'cm_companys',
    id: 'com_homepage',
    text: '公司主页',
    text_en: 'Official website',
    key: 'mg_homepage',
    value: '',
    rules: 'require',
    components: 'cust-homepage',
  },
  {
    table: 'cm_companys',
    id: 'com_introduction',
    text: '公司简介',
    text_en: 'Company Profile',
    key: 'mg_introduction',
    value: '',
    rules: 'require',
    components: 'cust-introduction',
  },
  {
    table: 'cm_companys',
    id: 'unload_port',
    text: '目的港',
    text_en: 'Destination',
    key: 'mg_port',
    value: '',
    rules: 'require',
    components: 'unload-port',
  },
  {
    table: 'cm_companys',
    id: 'forwarder_cust_com_id',
    text: '指定货代',
    text_en: 'Designated forwarder',
    key: 'mg_forwarder',
    value: {
      cust_com_id: '',
    },
    rules: 'require',
    components: 'forwarder',
  },
  {
    table: 'cm_companys',
    id: 'forwarder_cust_id',
    text: '指定货代联系人',
    text_en: 'Designated forwarder contact',
    key: 'mg_forwarder',
    value: {
      cust_id: '',
    },
    rules: 'require',
  },
  {
    table: 'cm_companys',
    id: 'assess_sales',
    text: '年销售额',
    text_en: 'Annual value',
    key: 'mg_assess',
    value: {
      mg_sales: '',
    },
    rules: 'require',
    components: 'sales-amount',
  },
  {
    table: 'cm_companys',
    id: 'assess_credit_line',
    text: '公司授信额度',
    text_en: 'Company credit Limit',
    key: 'mg_assess',
    value: {
      credit_line: '',
    },
    rules: 'require',
    components: 'credit-line',
  },
  {
    table: 'cm_companys',
    id: 'assess_insurance_amount',
    text: '中信保额度',
    text_en: 'CITIC Insurance Limit',
    key: 'mg_assess',
    value: {
      insurance_amount: '',
    },
    rules: 'require',
    components: 'insurance-amount',
  },
  {
    table: 'cm_companys',
    id: 'staff_size',
    text: '员工数量',
    text_en: 'Number of employees',
    key: 'mg_staff_size',
    value: '',
    rules: 'require',
    components: 'staff-size',
  },
  {
    table: 'cust_company',
    id: 'payment_id',
    text: '收款方式',
    text_en: 'Payment Terms',
    key: 'payment_id',
    value: '',
    rules: 'require',
    components: 'remittance',
  },
  {
    table: 'cust_company',
    id: 'audit_status',
    text: '审批状态',
    text_en: 'Approve Status',
    key: 'audit_status',
    value: '',
    rules: 'require',
  },
  {
    table: 'cust_company',
    id: 'cust_nature',
    text: '客户类型',
    text_en: 'Enterprise Nature',
    key: 'cust_nature',
    value: '',
    rules: 'require',
    components: 'cust-nature',
  },
  {
    table: 'cust_company',
    id: 'cust_level',
    text: '客户等级',
    text_en: 'Customer level',
    key: 'cust_level',
    value: '',
    rules: 'require',
    components: 'cust-level',
  },
  {
    table: 'cust_company',
    id: 'cust_profit',
    text: '目标利润率',
    text_en: 'Target profit margin',
    key: 'cust_profit',
    value: '',
    rules: 'require',
    components: 'cust-profit',
  },
  {
    table: 'cust_company',
    id: 'interest_rate',
    text: '日利率',
    text_en: 'Interest rate',
    key: 'interest_rate',
    value: '',
    rules: 'require',
    components: 'interest-rate',
  },
  {
    table: 'cust_company',
    id: 'id_code',
    text: 'ERP号',
    text_en: 'ERP NO.',
    key: 'id_code',
    value: '',
    rules: 'require',
    bill_check: 'sc',
    components: 'id-code',
  },
  {
    table: 'cust_company',
    id: 'receive_bank_id',
    text: '我方银行',
    text_en: 'Beneficiary Bank',
    key: 'receive_bank_id',
    value: '',
    rules: 'require',
    components: 'receive-bank',
  },
  {
    table: 'cust_company',
    id: 'is_agent',
    text: '采购代理',
    text_en: 'Purchasing agent',
    key: 'is_agent',
    value: '',
    rules: '',
    components: 'is-agent',
  },
  {
    table: 'cust_company',
    id: 'agent_price',
    text: '代理价格',
    text_en: 'Agency price',
    key: 'agent_price',
    value: '',
    rules: '',
    components: 'agent-price',
  },
  {
    table: 'cust_company',
    id: 'cust_code',
    text: '代码',
    text_en: 'Code',
    key: 'cust_code',
    value: '',
    rules: 'require',
    components: 'cust-code',
  },
  {
    table: 'cust_company',
    id: 'edi_buyer_no',
    text: '中信保买家代码',
    text_en: 'CITIC Insurance Buyer Code',
    key: 'edi_buyer_no',
    value: '',
    rules: 'require',
    components: 'edi-buyer-no',
  },
  {
    table: 'cust_company',
    id: 'legal_id',
    text: '法人公司',
    text_en: 'Corporate company',
    key: 'legal_id',
    value: '',
    rules: 'require',
    components: 'legal-com',
  },
  {
    table: 'cust_company',
    id: 'is_equity',
    text: '内部客商',
    text_en: 'Internal business',
    key: 'is_equity',
    value: '',
    rules: 'require',
    components: 'is-equity',
  },
  {
    table: 'cust_company',
    id: 'currency',
    text: '币种',
    text_en: 'Currency',
    key: 'currency',
    value: '',
    rules: 'require',
    components: 'currency',
  },
  {
    table: 'cust_company',
    id: 'trade_term',
    text: '贸易方式',
    text_en: 'Trade Terms',
    key: 'trade_term',
    value: '',
    rules: 'require',
    components: 'trade-term',
  },
  {
    table: 'cm_companys',
    id: 'main_mark',
    text: '正唛',
    text_en: 'Positive mark',
    key: 'mg_main_mark',
    value: {text: ''},
    rules: 'require',
    components: 'main-mark',
  },
  {
    table: 'cm_companys',
    id: 'side_mark',
    text: '侧唛',
    text_en: 'Side mark',
    key: 'mg_side_mark',
    value: {text: ''},
    rules: 'require',
    components: 'side-mark',
  },
  {
    table: 'cm_companys',
    id: 'our_forwarder_cus_com_id',
    text: '我方货代',
    text_en: 'Our forwarder',
    key: 'mg_our_forwarder',
    value: {
      cust_com_id: '',
    },
    rules: 'require',
    components: 'our-forwarder',
  },
  {
    table: 'cm_companys',
    id: 'our_forwarder_cust_id',
    text: '我方货代-联系人',
    text_en: 'Our forwarder contact',
    key: 'mg_our_forwarder',
    value: {
      cust_id: '',
    },
    rules: 'require',
  },
  {
    table: 'cm_companys',
    id: 'cust_consignees',
    text: '收货人',
    text_en: 'Consignee',
    key: 'mg_consignees',
    value: [],
    rules: 'require',
    components: 'consignees',
  },
  {
    table: 'cm_companys',
    id: 'consignee_tax_no',
    text: '收货人税号',
    text_en: 'Consignee Tax NO.',
    key: 'mg_consignee_tax_no',
    value: '',
    rules: 'require',
    components: 'consignee-tax-no',
  },
  {
    table: 'cm_companys',
    id: 'edi_buyer_name',
    text: '中信保买方名称',
    text_en: "CITIC Insurance Buyer's Name",
    key: 'mg_edi_buyer_name',
    value: '',
    rules: 'require',
    components: 'edi-buyer-name',
  },
  {
    table: 'cm_companys',
    id: 'credits_cecic_payout_ratio',
    text: '中信保赔付比例',
    text_en: "CITIC Insurance's compensation ratio",
    key: 'mg_credits_cecic_payout_ratio',
    value: '',
    rules: 'require',
    components: 'credits-cecic-payout-ratio',
  },
  {
    table: 'cm_companys',
    id: 'credits_cecic_valid_date',
    text: '中信保额度有效期',
    text_en: 'CITIC Insurance Limit Validity Period',
    key: 'mg_credits_cecic_valid_date',
    value: '',
    rules: 'require',
    components: 'credits-cecic-valid-date',
  },
  {
    table: 'cm_companys',
    id: 'credits_com_valid_date',
    text: '公司授信额度有效期',
    text_en: 'Company credit Limit Validity Period',
    key: 'mg_credits_com_valid_date',
    value: '',
    rules: 'require',
    components: 'credits-com-valid-date',
  },
  {
    table: 'cm_companys',
    id: 'notifier',
    text: '通知人',
    text_en: 'Notifier',
    key: 'mg_notifier',
    value: '',
    rules: 'require',
    components: 'notifier',
  },
  {
    table: 'cm_companys',
    id: 'notifier_tax_no',
    text: '通知人税号',
    text_en: 'Notifier Tax NO.',
    key: 'mg_notifier_tax_no',
    value: '',
    rules: 'require',
    components: 'notifier-tax-no',
  },
  {
    table: 'cm_companys',
    id: 'load_port',
    text: '启运港',
    text_en: 'Departure port',
    key: 'mg_load_port',
    value: '',
    rules: 'require',
    components: 'load-port',
  },
]

let special = [] // 个别公司定制字段，加上com_id

export default {
  common,
  special
}