/* eslint-disable */
export let common = [
  {
    table: 'cust_company',
    id: 'com_name',
    text: '公司',
    text_en: 'Company',
    key: 'com_name',
    value: '',
    rules: 'require',
    components: 'com-name',
  },
  {
    table: 'cust_company',
    id: 'cust_no',
    text: '编号',
    text_en: 'NO.',
    key: 'cust_no',
    value: '',
    rules: 'require',
    components: 'cust-no',
  },
  {
    table: 'cust_company',
    id: 'cust_owner',
    text: '采购经理',
    text_en: 'Account',
    key: 'cust_owner',
    value: '',
    rules: 'require',
    components: 'cust-owner',
  },
  {
    table: 'cm_companys',
    id: 'social_code',
    text: '税号',
    text_en: 'Tax NO.',
    key: 'mg_social_code',
    value: '',
    rules: 'require',
    components: 'social-code',
  },
  {
    table: 'cm_companys',
    id: 'raw_material',
    text: '关键原材料',
    text_en: 'Key raw materials',
    key: 'mg_raw_material',
    value: '',
    rules: 'require',
    components: 'raw-material',
  },
  {
    table: 'cust_company',
    id: 'com_nick',
    text: '公司简称',
    text_en: 'Abbreviation',
    key: 'com_nick',
    value: '',
    rules: 'require',
    components: 'com-nick',
  },
  {
    table: 'cust_company',
    id: 'com_type',
    text: '企业类型',
    text_en: 'Enterprise Owned',
    key: 'com_type',
    value: '',
    rules: 'require',
    components: 'com-type',
  },
  {
    table: 'cm_companys',
    id: 'register_date',
    text: '成立日期',
    text_en: 'Date of establishment',
    key: 'mg_register_date',
    value: '',
    rules: 'require',
    components: 'register-date',
  },
  {
    table: 'cm_companys',
    id: 'prod_sorts',
    text: '品类',
    text_en: 'Category',
    key: '',
    value: '',
    rules: 'require',
    components: 'prod-sorts',
  },
  {
    table: 'cust_company',
    id: 'address',
    text: '地址',
    text_en: 'Address',
    key: 'address',
    value: '',
    rules: 'require',
    components: 'cust-address',
  },
  {
    table: 'cm_companys',
    id: 'registered_capital',
    text: '注册资本',
    text_en: 'Registered capital',
    key: 'mg_registered_capital',
    value: '',
    rules: 'require',
    components: 'registered-capital',
  },
  {
    table: 'cm_companys',
    id: 'year_capacity',
    text: '年产值',
    text_en: 'Annual value',
    key: 'mg_year_capacity',
    value: '',
    rules: 'require',
    components: 'year-capacity',
  },
  {
    table: 'cm_companys',
    id: 'prod_address',
    text: '生产地址',
    text_en: 'Factory address',
    key: 'mg_prod_address',
    value: '',
    rules: 'require',
    components: 'prod-address',
  },
  {
    table: 'cm_companys',
    id: 'place_area',
    text: '厂房面积',
    text_en: 'Plant area',
    key: 'mg_place_area',
    value: '',
    rules: '',
    components: 'place-area',
  },
  {
    table: 'cm_companys',
    id: 'place_type',
    text: '厂房类型',
    text_en: 'Plant type',
    key: 'mg_place_type',
    value: '',
    rules: '',
  },
  {
    table: 'cm_companys',
    id: 'main_prods',
    text: '主要产品',
    text_en: 'Main products',
    key: 'mg_main_prods',
    value: '',
    rules: '',
    components: 'main-prods',
  },
  {
    table: 'cm_companys',
    id: 'staff_size',
    text: '员工数量',
    text_en: 'Number of employees',
    key: 'mg_staff_size',
    value: '',
    rules: '',
    components: 'staff-size',
  },
  {
    table: 'cm_companys',
    id: 'main_process',
    text: '主要工艺',
    text_en: 'Main process',
    key: 'mg_main_process',
    value: '',
    rules: '',
    components: 'main-process',
  },
  {
    table: 'cm_companys',
    id: 'contributed_capital',
    text: '实缴资本',
    text_en: 'Paid-in capital',
    key: 'mg_contributed_capital',
    value: '',
    rules: 'require',
    components: 'contributed-capital',
  },
  {
    table: 'cm_companys',
    id: 'month_capacity',
    text: '月产能',
    text_en: 'Monthly capacity',
    key: 'mg_month_capacity',
    value: '',
    rules: 'require',
    components: 'month-capacity',
  },
  {
    table: 'cm_companys',
    id: 'service_years',
    text: '实控人从业年限',
    text_en: 'Working years',
    key: 'mg_service_years',
    value: '',
    rules: 'require',
    components: 'service-years',
  },
  {
    table: 'cm_companys',
    id: 'capacity_proportion',
    text: '本公司所占产能比例',
    text_en: 'Capacity ratio',
    key: 'mg_capacity_proportion',
    value: '',
    rules: 'require',
    components: 'capacity-proportion',
  },
  {
    table: 'cm_companys',
    id: 'com_mail',
    text: '公司邮箱',
    text_en: 'Company email',
    key: 'mg_com_mail',
    value: '',
    rules: 'require',
    components: 'com-mail',
  },
  {
    table: 'cm_companys',
    id: 'business_license',
    text: '营业执照',
    text_en: 'business license',
    key: 'mg_business_license',
    value: [],
    rules: 'require',
    components: 'business-license',
  },
  {
    table: 'cm_companys',
    id: 'main_equipment',
    text: '主要设备和仪器',
    text_en: 'Main equipment and instruments',
    key: 'mg_equipment',
    value: '',
    rules: 'require',
    components: 'main-equipment',
  },
  {
    table: 'cm_companys',
    id: 'bad_credit',
    text: '不良信用说明',
    text_en: 'Bad credit description',
    key: 'mg_bad_credit',
    value: '',
    rules: 'require',
    components: 'bad-credit',
  },
  {
    table: 'cust_company',
    id: 'com_phone',
    text: '公司电话',
    text_en: 'Company phone',
    key: 'com_phone',
    value: '',
    rules: 'require',
    components: 'com-phone',
  },
  {
    table: 'cm_companys',
    id: 'credit_info',
    text: '国家企业信用公示',
    text_en: 'National corporate credit publicity',
    key: 'mg_credit_info',
    value: '',
    rules: 'require',
    components: 'credit-info',
  },
  {
    table: 'cm_companys',
    id: 'credit_report',
    text: '资信报告',
    text_en: 'Credit report',
    key: 'mg_credit_report',
    value: [],
    rules: 'require',
    components: 'credit-report',
  },
  {
    table: 'cm_companys',
    id: 'quality_auth',
    text: '质量认证',
    text_en: 'Quality Certification',
    key: 'mg_quality',
    value: [],
    rules: 'require',
    components: 'quality-auth',
  },
  {
    table: 'cm_companys',
    id: 'report_attach',
    text: '信用报告',
    text_en: 'Credit Report',
    key: 'mg_report_attach',
    value: [],
    rules: 'require',
    components: 'report-attach',
  },
  {
    table: 'cm_companys',
    id: 'full_view',
    text: '工厂现场',
    text_en: 'Factory site',
    key: 'mg_full_view',
    value: [],
    rules: 'require',
    components: 'full-view',
  },
  {
    table: 'cm_companys',
    id: 'com_homepage',
    text: '公司主页',
    text_en: 'Official website',
    key: 'mg_homepage',
    value: '',
    rules: 'require',
    components: 'cust-homepage',
  },
  {
    table: 'cm_companys',
    id: 'pay_type',
    text: '支付方式',
    text_en: 'Payment method',
    key: 'mg_pay_type',
    value: '',
    rules: 'require',
    components: 'pay-type',
  },
  {
    table: 'cm_companys',
    id: 'export_region',
    text: '出口地区',
    text_en: 'Export area',
    key: 'mg_export_region',
    value: [],
    rules: 'require',
    components: 'export-region',
  },
  {
    table: 'cm_companys',
    id: 'export_country',
    text: '出口国家',
    text_en: 'Export country',
    key: 'mg_export_country',
    value: [],
    rules: 'require',
    components: 'export-country',
  },
  {
    table: 'cm_companys',
    id: 'inout_code',
    text: '企业进出口代码',
    text_en: 'IEC',
    key: 'mg_inout_code',
    value: '',
    rules: 'require',
    components: 'inout-code',
  },
  {
    table: 'cm_companys',
    id: 'registration_form',
    text: '对外贸易备案登记',
    text_en: 'Foreign trade record registration',
    key: 'mg_registration_form',
    value: [],
    rules: 'require',
    components: 'registration-form',
  },
  {
    table: 'cm_companys',
    id: 'com_introduction',
    text: '公司简介',
    text_en: 'Company Profile',
    key: 'mg_introduction',
    value: '',
    rules: 'require',
    components: 'cust-introduction',
  },
  {
    table: 'cust_company',
    id: 'audit_status',
    text: '审批',
    text_en: 'Approve Status',
    key: 'audit_status',
    value: '',
    rules: 'require',
  },
  {
    table: 'cust_company',
    id: 'payment_id',
    text: '付款方式',
    text_en: 'Payment Terms',
    key: 'payment_id',
    value: '',
    rules: 'require',
    bill_check: 'sc',
    components: 'payment',
  },
  {
    table: 'cust_company',
    id: 'is_equity',
    text: '内部客商',
    text_en: 'Internal business',
    key: 'is_equity',
    value: '',
    rules: '',
    components: 'is-equity',
  },
  {
    table: 'cust_company_bank',
    id: 'bank_id',
    text: '银行',
    text_en: 'Bank',
    key: 'bank_id',
    value: '',
    rules: 'require',
    bill_check: 'sc',
  },
  {
    table: 'cust_company',
    id: 'country_id',
    text: '国家',
    text_en: 'Country',
    key: 'country_id',
    value: '',
    rules: 'require',
    components: 'cust-country',
  },
  {
    table: 'cm_companys',
    id: 'city_id',
    text: '城市',
    text_en: 'City',
    key: 'mg_city',
    value: '',
    rules: 'require',
    components: 'cust-city',
  },
  {
    table: 'cust_company',
    id: 'cust_code',
    text: '代码',
    text_en: 'Code',
    key: 'cust_code',
    value: '',
    rules: 'require',
    components: 'cust-code',
  },
  {
    table: 'cust_company',
    id: 'id_code',
    text: 'ERP号',
    text_en: 'ERP NO.',
    key: 'id_code',
    value: '',
    rules: 'require',
    components: 'id-code',
  },
  {
    table: 'cust_company',
    id: 'cust_profit',
    text: '目标利润率',
    text_en: 'Target profit margin',
    key: 'cust_profit',
    value: '',
    rules: 'require',
    components: 'cust-profit',
  },
  {
    table: 'cust_company',
    id: 'profit_rate',
    text: '利润率',
    text_en: 'Profit margin',
    key: 'profit_rate',
    value: '',
    rules: 'require',
    components: 'profit-rate',
  },
  {
    table: 'cust_company',
    id: 'legal_id',
    text: '法人公司',
    text_en: 'Corporate company',
    key: 'legal_id',
    value: '',
    rules: 'require',
    components: 'legal-com',
  },
  {
    table: 'cm_companys',
    id: 'cooperation_agreement',
    text: '合作协议',
    text_en: 'Cooperation agreement',
    key: 'mg_cooperation_agreement',
    value: [],
    rules: 'require',
    components: 'cooperation-agreement',
  },
  {
    table: 'cm_companys',
    id: 'legal_representative',
    text: '法人代表',
    text_en: 'Legal representative',
    key: 'mg_legal',
    value: '',
    rules: 'require',
    components: 'sup-legal',
  },
  {
    table: 'cm_companys',
    id: 'tax_invoice',
    text: '发票税率',
    text_en: 'Invoice tax rate',
    key: 'mg_tax_invoice',
    value: '',
    rules: 'require',
    components: 'tax-invoice',
  },
  {
    table: 'cm_companys',
    id: 'bsci_files',
    text: 'BSCI文件',
    text_en: 'BSCI',
    key: 'mg_bsci_files',
    value: [],
    rules: 'require',
    components: 'bsci-files',
  },
  {
    table: 'cm_companys',
    id: 'inspect_report',
    text: '验厂报告',
    text_en: 'Inspection report',
    key: 'mg_inspect_report',
    value: [],
    rules: 'require',
    components: 'inspect-report',
  },
  {
    table: 'cm_companys',
    id: 'credit_rating',
    text: '信用等级',
    text_en: 'Credit Level',
    key: 'mg_credit',
    value: {
      mg_rating: '',
    },
    rules: 'require',
    components: 'credit-level',
  },
]

let special = []  //个别公司定制字段，加上com_id

export default {
  common,
  special
}