export default {
  demo: {
    url: 'api/demo/world', pretty (raw) {
      return raw.value
    }
  },
  billSearch: {url: '/api/business/billSearch', loading: true, method: 'get'},
  queryCustComList: {url: '/api/crm/queryCustComList', loading: true, method: 'get'},
  createCustInfo: {url: '/api/crm/createCustInfo', loading: true, method: 'post'},
  preProd: {url2: '/api/product/preProd', method: 'get'},
  queryProdInfo: {url: '/api/product/queryProdInfo', loading: true, method: 'get'},
  upsertProduct: {url: '/api/product/upsertProduct', method: 'post'},
  upsertProduct2: {url2: '/api/product/upsertProduct', method: 'post'},
  queryProductList: {url2: '/api/product/queryProductList', method: 'get'},
  deleteBill: {url: '/api/business/deleteBill', method: 'post'},
  deleteBill2: {url2: '/api/business/deleteBill', method: 'post'},
  preBill: {url: '/api/business/preBill', loading: true, method: 'post'},
  queryPiProd: {url: '/api/business/queryPiProd', loading: true, method: 'get'},
  updatePiProd: {url: '/api/business/updatePiProd', method: 'post'},
  addBillProd: {url: '/api/business/addBillProd', loading: true, method: 'post'},
  addBillProd2: {url: '/api/business/addBillProd', loading: true, method: 'post'},
  deleteBillProd: {url2: '/api/business/deleteBillProd', method: 'post'},
  upsertBillMain: {url: '/api/business/upsertBillMain', method: 'post'},
  billMainInfo: {url: '/api/business/billMainInfo', loading: true, method: 'get'},
  queryBillProdList: {url: '/api/business/queryBillProdList', loading: true, method: 'get'},
  querySellerInfo: {url: '/api/business/querySellerInfo', loading: true, method: 'get'},
  queryBuyerInfo: {url: '/api/business/queryBuyerInfo', loading: true, method: 'get'},
  getTemplate: {url: '/api/support/getTemplate', loading: true, method: 'get'},
  setTemplate: {url: '/api/support/setTemplate', method: 'post'},
  applyBillOutput: {url: '/api/business/applyBillOutput', method: 'post'},
  queryComBankList: {url: '/api/crm/queryComBankList', loading: true}, method: 'get',
  querySettle: {url: '/api/business/querySettle', loading: true, method: 'get'},
  createSettle: {url: '/api/business/createSettle', method: 'post'},
  queryCiqInspections: {url: '/api/business/queryCiqInspections', loading: true},
  updateCiqInspections: {url: '/api/business/updateCiqInspections'},
  addPiContracts: {url: '/api/business/addPiContracts'},
  queryStaffList: {url: '/api/manage/queryStaffList', loading: true, method: 'get'},
  getTimeLineEtd: {url: '/api/business/getTimeLineEtd'},
  resetMissionEtd: {url: '/api/business/resetMissionEtd'},
  queryBillInvoices: {url: '/api/business/queryBillInvoices', loading: true},
  upsertBillInvoice: {url: '/api/business/upsertBillInvoice'},
  queryPiProdList: {url: '/api/business/queryPiProdList', loading: true, method: 'get'},
  queryUnbookProdList: {url: '/api/business/queryUnbookProdList', loading: true, method: 'get'},
  prepareBillInvoice: {url: '/api/business/prepareBillInvoice', loading: true},
  upsertBookLoad: {url: '/api/business/upsertBookLoad', method: 'post'},
  queryBookorderListByContract: {url: '/api/business/queryBookorderListByContract', loading: true},
  queryPiProdPurchaseList: {url: '/api/business/queryPiProdPurchaseList', loading: true},
  querySimpleBill: {url2: '/api/business/querySimpleBill', loading: true},
  querySimpleProd: {url2: '/api/product/querySimpleProd', loading: true},
  queryProdsByType: {url: '/api/business/queryProdsByType', loading: true},
  queryMgbField: {url: '/api/support/getMgbField', loading: false},
  updateAttachFile: {url: '/api/support/updateAttachFile', loading: true},
  updateRemark: {url: '/api/support/updateRemark', method: 'post'},
  getMgbField: {url: '/api/support/getMgbField', method: 'get'},
  refreshMobileMall: {url: '/api/manage/refreshMobileMall', loadding: true},
  queryPuProd: {url: '/api/business/queryPuProd', loadding: true, method: 'get'},
  lazyCreateQuote: {url: 'api/business/lazyCreateQuote', loadding: true, method: 'post'},
  queryQuoteProds: {url: 'api/business/queryQuoteProds', loadding: true, method: 'get'},
  queryBookLoadInfo: {url: 'api/business/queryBookLoadInfo', loadding: true, method: 'get'},
  preSettle: {url: '/api/business/preSettle'},
  upsertPayment: {url2: '/api/business/upsertPayment', method: 'post'},
  queryCustCompany: {url: '/api/crm/queryCustCompany', method: 'get'},
  updateCustCompany: {url: '/api/crm/updateCustCompany', method: 'post'},
  queryCustUser: {url: '/api/crm/queryCustUser', method: 'get'},
  queryCustUserList: {url2: '/api/crm/queryCustUserList', method: 'get'},
  upsertMgbFieldArray: {url: '/api/support/upsertMgbFieldArray', loadding: true, method: 'post'},
  queryBillFullInfo: {url: '/api/business/queryBillFullInfo', loadding: true, method: 'get'},
  loadingProcess: {url2: '/api/business/loadingProcess', method: 'post'},
  verifyCust: {url: '/api/crm/verifyCust'},
  queryBookInvoice: {url: '/api/business/queryBookInvoice', loading: true},
  createBookSegotiables: {url: '/api/business/createBookSegotiables', loading: true},
  createBookInvoice: {url: '/api/business/createBookInvoice', loading: true},
  upsertCustUser: {url: '/api/crm/upsertCustUser', method: 'post'},
  queryPuVat: {url: '/api/business/queryPuVat'},
  queryBkVat: {url: '/api/business/queryBkVat'},
  updateBillInvoice: {url: '/api/business/updateBillInvoice', method: 'post'},
  validateBill: {url2: '/api/business/validateBill', loadding: true, method: 'post'},
  createReceipt: {url2: '/api//business/createReceipt', loadding: true, method: 'post'},
  addAttachment: {url: '/api/support/addAttachment', loadding: true, method: 'post'},
  queryAllAttach: {url: '/api/support/queryAllAttach', loadding: true, method: 'get'},
  removetAtachment: {url: '/api/support/removetAtachment', loadding: true, method: 'post'},
  modifyAttachment: {url: '/api/support/modifyAttachment', loadding: true, method: 'post'},
  queryProdFactoryByProdId: {url: '/api/product/queryProdFactoryByProdId', loadding: true, method: 'post'},
  preApprove: {url: '/api/manage/preApprove', loadding: true, method: 'post'},
  noApproveBusiFee: {url2: '/api/manage/noApproveBusiFee', loadding: true, method: 'post'},
  commitApprove: {url: '/api/manage/commitApprove', loadding: true, method: 'post'},
  startVerify: {url2: '/api/business/startVerify'},
  queryVerifyResult: {url2: '/api/business/queryVerifyResult', method: 'get'},
  setMailTemp: {url: '/api/support/setMailTemplate', method: 'post'},
  getMailTemp: {url: '/api/support/getMailTemplate', method: 'get'},
  queryBusiFeeList: {url: 'api/business/queryBusiFeeList', method: 'get'},
  prepayMailSend: {url: '/api/mail/prepayMailSend', method: 'post'},
  sendMail: {url: '/api/mail/sendMail', loadding: true, method: 'post'},
  sendCatalog: {url: '/api/mail/sendCatalog', loadding: true, method: 'post'},
  batchSendMail: {url: '/api/mail/batchSendMail', loadding: true, method: 'post'},
  setJsTemp: {url: '/api/support/setJsTemplate'},
  getJsTemp: {url: '/api/support/getJsTemplate'},
  queryGrossRate: {url2: '/api/business/queryGrossRate'},
  flowEngine: {url: '/api/manage/flowEngine', method: 'post'},
  queryInqProd: {url: '/api/business/queryInqProd'},
  updateInqProd: {url: '/api/business/updateInqProd'},
  queryReceipt: {url: '/api/business/queryReceipt'},
  queryClaimList: {url: '/api/business/queryClaimList'},
  preTest: {url2: '/api/business/preTest'},
  upsertTest: {url2: '/api/business/upsertTest'},
  queryTestInfo: {url2: '/api/buy/queryTestInfo', loadding: true},
  preSample: {url2: '/api/business/preSample'},
  upsertSample: {url2: '/api/business/upsertSample'},
  writeOffReceiptClaim: {url2: '/api/business/writeOffReceiptClaim'},
  queryWriteOffDetails: {url: '/api/business/queryWriteOffDetails'},
  querySampleInfo: {url2: '/api/business/querySampleInfo', loadding: true},
  cancelApprove: {url: '/api/manage/cancelApprove', method: 'post'},
  queryPiClaim: {url: '/api/business/queryPiClaims', method: 'get'},
  queryPuOrders: {url: '/api/business/queryPuOrders', method: 'get'},
  updatePuOrder: {url: '/api/business/updatePuOrder', method: 'post'},
  queryBookLoadOrder: {url: 'api/business/queryBookLoadOrder', method: 'get'},
  queryProdInfos: {url: '/api/product/queryProdInfos', method: 'get'},
  updateBusiFee: {url2: '/api/business/updateBusiFee', method: 'post'},
  updateBusiFeeBill: {url2: '/api/business/updateBusiFeeBill'},
  queryNature: {url: '/api/product/queryNature', method: 'get'},
  queryPiNature: {url: '/api/business/queryPiNature', method: 'get'},
  genSetPWdToken: {url2: '/api/system/genSetPWdToken', method: 'get', loadding: false}
}
