export default {
  key: 'im',
  timelines: [
    {
      key: "im_bill",
      value: "进口订单",
      name: "进口订单",
      name_en: "进口订单",
      isSelected: true,
      part: "PuBill",
    },
    {
      key: "shipping_plan",
      value: "备货计划",
      name: "备货计划",
      name_en: "Shipping Plan",
      isSelected: true,
      part: "PuShippingPlan",
    },
    {
      key: "artwork",
      value: "包装稿",
      name: "包装稿",
      name_en: "Artwork",
      isSelected: true,
      part: "",
    },
    {
      key: "marks",
      value: "唛头",
      name: "唛头",
      name_en: "Marks",
      isSelected: true,
      part: "",
    },
    {
      key: "inspection",
      value: "验货",
      name: "验货",
      name_en: "Inspection",
      isSelected: true,
      part: "",
    },
    {
      key: "",
      value: "进口订舱",
      name: "进口订舱",
      name_en: "",
      isSelected: true,
      part: "PuBooking",
    },
    {
      key: "warehousing",
      value: "入库",
      name: "入库",
      name_en: "Warehousing",
      isSelected: true,
      part: "",
    },
    {
      key: "out_of_stock",
      value: "出库",
      name: "出库",
      name_en: "Out of stock",
      isSelected: true,
      part: "",
    },
    {
      key: "settlement",
      value: "采购结算",
      name: "采购结算",
      name_en: "Settlement",
      isSelected: true,
      part: "PuSettlement",
    },
    {
      key: "billing_notice",
      value: "开票通知",
      name: "开票通知",
      name_en: "Billing notice",
      isSelected: true,
      part: "",
    },
    {
      key: "payment",
      value: "付款",
      name: "付款",
      name_en: "Payment",
      isSelected: true,
      part: "ImBkFee",
    },
    {
      key: "signed",
      value: "合同回签",
      name: "合同回签",
      name_en: "Signed",
      isSelected: true,
      part: "",
    },
    // {key: 'history', value: '变更记录', name: '变更记录', name_en: 'History', isSelected: true,part: ''},
    {
      key: "memorandum",
      value: "备忘录",
      name: "备忘录",
      name_en: "Memorandum",
      isSelected: true,
      part: "",
    },
    {
      key: "document",
      value: "文档",
      name: "文档",
      name_en: "Document",
      isSelected: true,
      part: "",
    },
  ]
}
