export default {
  key: 'pu',
  timelines: [
    {
      key: "po",
      value: "合同",
      name: "合同",
      name_en: "PO",
      isSelected: true,
      part: "PuBill",
    },
    {
      key: "shipping_plan",
      value: "备货计划",
      name: "备货计划",
      name_en: "Shipping Plan",
      isSelected: true,
      part: "PuShippingPlan",
    },
    // {
    //   key: "artwork",
    //   value: "包装稿",
    //   name: "包装稿",
    //   name_en: "Artwork",
    //   isSelected: true,
    //   part: "",
    // },
    // {
    //   key: "marks",
    //   value: "唛头",
    //   name: "唛头",
    //   name_en: "Marks",
    //   isSelected: true,
    //   part: "",
    // },
    // {
    //   key: "inspection",
    //   value: "验货",
    //   name: "验货",
    //   name_en: "Inspection",
    //   isSelected: true,
    //   part: "",
    // },
    {
      key: "warehousing",
      value: "入库",
      name: "入库",
      name_en: "Warehousing",
      isSelected: true,
      part: "PuWarehousing",
    },
    {
      key: "out_of_stock",
      value: "出库",
      name: "出库",
      name_en: "Out of stock",
      isSelected: true,
      part: "PuOutStock",
    },
    {
      key: "settlement",
      value: "采购结算",
      name: "采购结算",
      name_en: "Settlement",
      isSelected: true,
      part: "PuSettle",
    },
    {
      key: "billing_notice",
      value: "开票通知",
      name: "开票通知",
      name_en: "Billing notice",
      isSelected: true,
      part: "PuBillingNotice",
    },
    {
      key: "payment",
      value: "付款",
      name: "付款",
      name_en: "Payment",
      isSelected: true,
      part: "PuPayment",
    },
    {
      key: "signed",
      value: "PO回签",
      name: "PO回签",
      name_en: "PuSigned",
      isSelected: true,
      part: "PuSigned",
    },
    // {key: 'history', value: '变更记录', name: '变更记录', name_en: 'History', isSelected: true,part: ''},
    // {
    //   key: "memorandum",
    //   value: "备忘录",
    //   name: "备忘录",
    //   name_en: "Memorandum",
    //   isSelected: true,
    //   part: "",
    // },
    // {
    //   key: "document",
    //   value: "文档",
    //   name: "文档",
    //   name_en: "Document",
    //   isSelected: true,
    //   part: "",
    // },
  ]
}
