export default {
  key: 'sc_prod',
  timelines: [
    {
      key: "product",
      value: "产品",
      name: "产品",
      name_en: "Product",
      isSelected: true,
      part: "",
    },
    {
      key: "shipping_plan",
      value: "出运计划",
      name: "出运计划",
      name_en: "Shipping Plan",
      isSelected: true,
      part: "",
    },
    {
      key: "artwork",
      value: "包装稿",
      name: "包装稿",
      name_en: "Artwork",
      isSelected: true,
      part: "",
    },
    {
      key: "marks",
      value: "唛头",
      name: "唛头",
      name_en: "Marks",
      isSelected: true,
      part: "",
    },
    {
      key: "sample",
      value: "样品",
      name: "样品",
      name_en: "Sample",
      isSelected: true,
      part: "",
    },
    {
      key: "test",
      value: "检测",
      name: "检测",
      name_en: "Test",
      isSelected: true,
      part: "",
    },
    {
      key: "inspection",
      value: "验货",
      name: "验货",
      name_en: "Inspection",
      isSelected: true,
      part: "",
    },
    // {key: 'history', value: '变更记录', name: '变更记录', name_en: 'History', isSelected: true,part: ''},
    {
      key: "memorandum",
      value: "备忘录",
      name: "备忘录",
      name_en: "Memorandum",
      isSelected: true,
      part: "",
    },
    {
      key: "document",
      value: "文档",
      name: "文档",
      name_en: "Document",
      isSelected: true,
      part: "",
    },
  ]
}
