export default [
  {
    title: "Picture",
    title_en: "Picture",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_main_pic",
    display: [{ unit: "", sort: "", id: "main_pic" }],
  },
  {
    title: "Description",
    title_en: "Description",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_prod_desc",
    display: [
      { unit: "", sort: "", id: "prod_desc" },
    ],
  },
  {
    title: "Easy/Model",
    title_en: "Easy/Model",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [
      { unit: "", sort: "", id: "model" },
      { unit: "", sort: "", id: "original_prod_no" },
      { unit: "", sort: "", id: "supplier_no" },
    ],
  },
  {
    title: "S.Price",
    title_en: "S.Price",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_s_price",
    display: [{ unit: "", sort: "", id: "s_price" }],
  },
  {
    title: "C.Item/Barcode",
    title_en: "C.Item/Barcode",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_c_item_barcode",
    display: [{ unit: "", sort: "", id: "c_item_barcode" }],
  },
  {
    title: "C.Hscode/Tariff",
    title_en: "C.Hscode/Tariff",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_c_hscode_tariff",
    display: [{ unit: "", sort: "", id: "c_hscode_tariff" }],
  },
  {
    title: "Supplier",
    title_en: "Supplier",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_supplier",
    display: [{ unit: "", sort: "", id: "supplier" }],
  },
  {
    title: "Term/POL",
    title_en: "Term/POL",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_term_pol",
    display: [
      { unit: "", sort: "", id: "term_pol" },
    ],
  },
  {
    title: "Info",
    title_en: "Info",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_info",
    display: [
      { unit: "", sort: "", id: "info" },
    ],
  },
]