export default [
  {
    title: "序号",
    title_en: "NO",
    fixed: false,
    resizable: true,
    type: "index",
    display: [{ unit: "", sort: "", line: "", id: "index" }],
  },
  {
    title: "产品",
    title_en: "Product",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_main_pic",
    display: [{ unit: "", sort: "", line: "", id: "main_pic" }],
  },
  {
    title: "描述",
    title_en: "Description",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "2", id: "prod_name_en" },
      { unit: "", sort: "", line: "", id: "item_no" },
    ],
  },
  {
    title: "型号",
    title_en: "Model",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "model" },
      { unit: "", sort: "", line: "", id: "original_prod_no" },
    ],
  },
  {
    title: "数量",
    title_en: "Quantity",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "quantity" }],
  },
  {
    title: "销售单价",
    title_en: "Sell Price",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "sell_price" }],
  },
  {
    title: "实发",
    title_en: "Real Quantity",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "load_quantity" }],
  },
  {
    title: "金额",
    title_en: "Amount",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_amount",
    display: [{ unit: "", sort: "", line: "", id: "amount" }],
  },
  {
    title: "单箱毛体",
    title_en: "Single GW CBM",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_single_gw_cbm",
    display: [{ unit: "", sort: "", line: "", id: "single_gw_cbm" }],
  },
  {
    title: "毛件体",
    title_en: "G.W./CTN/CBM",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_gw_ctn_cbm",
    display: [{ unit: "", sort: "", line: "", id: "gw_ctn_cbm" }],
  },
  {
    title: "交货日",
    title_en: "Delivery date",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "crd_date" }],
  },
  {
    title: "进度",
    title_en: "Process",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "process_id" }],
  },
  {
    title: "状态",
    title_en: "Status",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_status",
    display: [{ unit: "", sort: "", line: "", id: "status" }],
  },
  {
    title: "供应商",
    title_en: "Supplier",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "seller_id" }],
  },
  {
    title: "操作",
    title_en: "Action",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_action",
    display: [{ unit: "", sort: "", line: "", id: "action" }],
  },
];
