export default [
  {
    title: "序号",
    title_en: "NO",
    fixed: false,
    resizable: true,
    type: "index",
    display: [{ unit: "", sort: "", line: "", id: "index" }],
  },
  {
    title: "型号",
    title_en: "Model",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "model" }],
  },
  {
    title: "爆炸图号",
    title_en: "Exploded No",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "exploded_no" }],
  },
  {
    title: "品名",
    title_en: "Product Name",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "prod_name_en" }],
  },
  {
    title: "工厂货号",
    title_en: "ERP No.",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "supplier_no" }],
  },
  {
    title: "销售单价",
    title_en: "Sell Price",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "sell_price" }],
  },
  {
    title: "数量",
    title_en: "Quantity",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "quantity" }],
  },
  {
    title: "金额",
    title_en: "Amount",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_amount",
    display: [{ unit: "", sort: "", line: "", id: "amount" }],
  },
  {
    title: "操作",
    title_en: "Action",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_action",
    display: [{ unit: "", sort: "", line: "", id: "action" }],
  },
];
