export default [
  {
    title: "序号",
    title_en: "NO",
    fixed: false,
    resizable: true,
    type: "index",
    display: [{ unit: "", sort: "", line: "", id: "index" }],
  },
  {
    title: "产品",
    title_en: "Product",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_main_pic",
    display: [{ unit: "", sort: "", line: "", id: "main_pic" }],
  },
  {
    title: "描述",
    title_en: "Description",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "2", id: "prod_name_en" },
    ],
  },
  {
    title: "货号",
    title_en: "Product No.",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "item_no" },
      { unit: "", sort: "", line: "", id: "model" },
    ],
  },
  {
    title: "供应商",
    title_en: "Supplier",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [{ unit: "", sort: "", line: "", id: "seller_id" }],
  },
  {
    title: "采购合同号",
    title_en: "Purchase NO.",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "purchase_no" }],
  },
  {
    title: "数量",
    title_en: "Quantity",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "quantity" }],
  },
  {
    title: "价格",
    title_en: "Price",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "pu_price" }],
  },
  {
    title: "金额",
    title_en: "Amount",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_amount",
    display: [{ unit: "", sort: "", line: "", id: "amount" }],
  },
  {
    title: "采购日期",
    title_en: "Valid Date",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "valid_date" }],
  },
  {
    title: "交付日期",
    title_en: "Delivery Date",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "delivery_date" }],
  },
  {
    title: "客户",
    title_en: "Buyer",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "com_legal" },
    ],
  },
  {
    title: "业务员",
    title_en: "Busi User",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "busi_user" },
    ],
  },
];
