export default [
  {
    title: "序号",
    title_en: "NO",
    fixed: false,
    resizable: true,
    type: "index",
    display: [{ unit: "", sort: "", line: "", id: "index" }],
  },
  {
    title: "产品",
    title_en: "Product",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_main_pic",
    display: [{ unit: "", sort: "", line: "", id: "main_pic" }],
  },
  {
    title: "描述",
    title_en: "Description",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "2", id: "prod_name_en" },
    ],
  },
  {
    title: "货号",
    title_en: "Product No.",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "item_no" },
      { unit: "", sort: "", line: "", id: "model" },
    ],
  },
  {
    title: "客户",
    title_en: "Customer",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [{ unit: "", sort: "", line: "", id: "sell_cust_com_id" }],
  },
  {
    title: "币种",
    title_en: "Currency",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "currency" }],
  },
  {
    title: "价格",
    title_en: "Price",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "qu_price" }],
  },
  {
    title: "数量",
    title_en: "Quantity",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "quantity" }],
  },
  {
    title: "报价日期",
    title_en: "Quote date",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "quote_date" }],
  },
  {
    title: "销售方",
    title_en: "Sell company",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "sell_comlegal_id" }],
  },
  {
    title: "业务信息",
    title_en: "Busi Info",
    fixed: false,
    resizable: true,
    type: "",
    slot: 'th_busi_info',
    display: [
      { unit: "", sort: "", line: "", id: "busi_info" },
    ],
  },
];
