export default [
  {
    title: "序号",
    title_en: "NO",
    fixed: false,
    resizable: true,
    type: "index",
    slot: "",
    display: [{ unit: "", sort: "", line: "", id: "index" }],
  },
  {
    title: "产品",
    title_en: "Product",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_main_pic",
    display: [{ unit: "", sort: "", id: "main_pic" }],
  },
  {
    title: "描述",
    title_en: "Description",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "2", id: "prod_name_en" },
      { unit: "", sort: "", line: "", id: "item_no" },
    ],
  },
  {
    title: "型号",
    title_en: "Model",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [
      { unit: "", sort: "", line: "", id: "model" },
      { unit: "", sort: "", line: "", id: "original_prod_no" },
    ],
  },
  {
    title: "销售数量",
    title_en: "Sell Quantity",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [{ unit: "", sort: "", line: "", id: "sell_quantity" }],
  },
  {
    title: "销售单价",
    title_en: "Sell Price",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [{ unit: "", sort: "", line: "", id: "sell_price" }],
  },
  {
    title: "金额",
    title_en: "Amount",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_amount",
    display: [{ unit: "", sort: "", line: "", id: "amount" }],
  },
  {
    title: "出运日/交货日",
    title_en: "ETD/D.D",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [
      { unit: "", sort: "", line: "", id: "etd_date" },
      { unit: "", sort: "", line: "", id: "delivery_date" },
    ],
  },
  {
    title: "毛件体",
    title_en: "G.W./CTN/CBM",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_gw_ctn_cbm",
    display: [{ unit: "", sort: "", line: "", id: "gw_ctn_cbm" }],
  },
];
