export default [
  {
    title: "产品",
    title_en: "Product",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_main_pic",
    display: [{ unit: "", sort: "", id: "main_pic" }],
  },
  {
    title: "描述",
    title_en: "Description",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [
      { unit: "", sort: "", id: "prod_name_en", line: '2' },
      { unit: "", sort: "", id: "item_no" },
    ],
  },
  {
    title: "型号",
    title_en: "Model",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [
      { unit: "", sort: "", id: "model" },
      { unit: "", sort: "", id: "original_prod_no" },
      { unit: "", sort: "", id: "supplier_no" },
    ],
  },
  {
    title: "规格",
    title_en: "Specifications",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [{ unit: "", sort: "", id: "prod_spec_en" }],
  },
  {
    title: "信息完整度",
    title_en: "Information integrity",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_info_integrity",
    display: [{ unit: "", sort: "", id: "info_integrity" }],
  },
  {
    title: "信息",
    title_en: "Information",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [
      { unit: "", sort: "", id: "owner_id" },
      { unit: "", sort: "", id: "create_date" },
    ],
  },
  {
    title: "上架",
    title_en: "On the shelf",
    fixed: false,
    resizable: true,
    type: "",
    slot: "",
    display: [
      { unit: "", sort: "", id: "update_user" },
      { unit: "", sort: "", id: "update_date" },
    ],
  },
  {
    title: "操作",
    title_en: "Action",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_action",
    display: [{ unit: "", sort: "", id: "action" }],
  },
]