export default [
  {
    title: "序号",
    title_en: "NO",
    fixed: false,
    resizable: true,
    type: "index",
    display: [{ unit: "", sort: "", line: "", id: "index" }],
  },
  {
    title: "产品",
    title_en: "Product",
    fixed: false,
    resizable: true,
    type: "",
    slot: "th_main_pic",
    display: [{ unit: "", sort: "", line: "", id: "main_pic" }],
  },
  {
    title: "描述",
    title_en: "Description",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "2", id: "prod_name_en" },
      { unit: "", sort: "", line: "", id: "item_no" },
    ],
  },
  {
    title: "型号",
    title_en: "Model",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "model" },
      { unit: "", sort: "", line: "", id: "original_prod_no" },
    ],
  },
  {
    title: "销售订单/计划出运",
    title_en: "SC/ETD",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "sc_etd" }],
    slot: "th_sc_etd",
  },
  {
    title: "供应商/承诺交货",
    title_en: "Supplier/D.D",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "sup_dd" }],
    slot: "th_sup_dd",
  },
  {
    title: "数量/实际交货",
    title_en: "QTY/CRD",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "qty_crd" }],
    slot: "th_qty_crd",
  },
  {
    title: "起运港/目的港",
    title_en: "POL/POD",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "load_port" },
      { unit: "", sort: "", line: "", id: "unload_port" },
    ],
  },
  {
    title: "毛件体",
    title_en: "G.W./CTN/CBM",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "gw_ctn_cbm" }],
  },
  {
    title: "备货进度",
    title_en: "备货进度",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "process_id" }],
  },
  {
    title: "客户",
    title_en: "Customer",
    fixed: false,
    resizable: true,
    type: "",
    display: [{ unit: "", sort: "", line: "", id: "buyer_id" }],
  },
  {
    title: "销售员/跟单员",
    title_en: "Sales/Merchandiser",
    fixed: false,
    resizable: true,
    type: "",
    display: [
      { unit: "", sort: "", line: "", id: "busi_user" },
      { unit: "", sort: "", line: "", id: "operator" },
    ],
  },
];
